[[pages]]
path = "app.py"
name = "ğŸ  Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_search_lyrics.py"
name = "ğŸ¼ ê°€ì‚¬ ê²€ìƒ‰"
icon = "ğŸ¼"

[[pages]]
path = "pages/2_ppt_generator.py"
name = "ğŸ’» ìˆ˜ë ¨íšŒìš© PPT ìƒì„±ê¸°"
icon = "ğŸ’»"

[[pages]]
path = "pages/3_youtube_bpm_code.py"
name = "ğŸ“Š BPM, Key ì°¾ê¸°"
icon = "ğŸ“Š"